# 日志等级:trace,debug,info,warn,fatal,mark,error,off
log_level: info

# 日志保留天数
log_daysToKeep: 7

# HTTP服务器端口
http_port: 7000

# 主人列表
master:

# 功能黑名单
blackList:
  # 屏蔽插件包
  - "examples"
  # 屏蔽单个插件
  - "examples/复读.js"
  # 屏蔽插件包内的单个插件
  - "examples/apps/复读.js"
